apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: image-processing-service
  namespace: default
  annotations:
    run.googleapis.com/launch-stage: GA
    run.googleapis.com/binary-authorization: "projects/PROJECT_ID/attestors/prod-attestor"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "30"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 50
      timeoutSeconds: 540
      serviceAccountName: image-processor-sa
      containers:
      - image: gcr.io/project-id/image-processor:v3.0.1
        name: image-processor
        ports:
        - name: http1
          containerPort: 5000
        env:
        - name: GCS_BUCKET_INPUT
          value: "image-uploads-bucket"
        - name: GCS_BUCKET_OUTPUT
          value: "processed-images-bucket"
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-config
              key: host
        - name: REDIS_PORT
          value: "6379"
        - name: IMAGE_MAX_SIZE_MB
          value: "50"
        - name: SUPPORTED_FORMATS
          value: "jpg,png,webp,gif"
        resources:
          limits:
            cpu: "8"
            memory: "8Gi"
          requests:
            cpu: "4"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /ping
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 30
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir:
          sizeLimit: 10Gi
  traffic:
  - percent: 100
    latestRevision: true