apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: default
  annotations:
    run.googleapis.com/launch-stage: GA
    run.googleapis.com/ingress: all
    run.googleapis.com/operation-id: api-gateway-deployment
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "5"
        autoscaling.knative.dev/maxScale: "200"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 2000
      timeoutSeconds: 60
      serviceAccountName: api-gateway-sa
      containers:
      - image: gcr.io/project-id/api-gateway:v6.0.0
        name: api-gateway
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: RATE_LIMIT_REQUESTS_PER_MINUTE
          value: "1000"
        - name: CORS_ALLOWED_ORIGINS
          value: "https://app.example.com,https://admin.example.com"
        - name: AUTH0_DOMAIN
          valueFrom:
            secretKeyRef:
              name: auth0-config
              key: domain
        - name: AUTH0_AUDIENCE
          valueFrom:
            secretKeyRef:
              name: auth0-config
              key: audience
        - name: BACKEND_SERVICES
          value: |
            {
              "auth": "https://user-authentication-service.run.app",
              "payment": "https://payment-processing-service.run.app",
              "email": "https://email-notification-service.run.app",
              "image": "https://image-processing-service.run.app",
              "analytics": "https://data-analytics-service.run.app"
            }
        - name: ENABLE_REQUEST_LOGGING
          value: "true"
        - name: ENABLE_TRACING
          value: "true"
        - name: TRACING_SAMPLE_RATE
          value: "0.1"
        - name: CACHE_PROVIDER
          value: "memcached"
        - name: MEMCACHED_SERVERS
          valueFrom:
            secretKeyRef:
              name: memcached-config
              key: servers
        resources:
          limits:
            cpu: "4"
            memory: "4Gi"
          requests:
            cpu: "2"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
            httpHeaders:
            - name: X-Health-Check
              value: "true"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
            httpHeaders:
            - name: X-Health-Check
              value: "true"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        startupProbe:
          httpGet:
            path: /health/startup
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 20
  traffic:
  - percent: 100
    latestRevision: true