apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: websocket-chat-service
  namespace: default
  annotations:
    run.googleapis.com/launch-stage: GA
    run.googleapis.com/ingress: all
    run.googleapis.com/sessionAffinity: "true"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "3"
        autoscaling.knative.dev/maxScale: "50"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 3600
      serviceAccountName: websocket-sa
      containers:
      - image: gcr.io/project-id/websocket-chat:v4.1.0
        name: websocket-chat
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: REDIS_CLUSTER_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: redis-cluster
              key: endpoint
        - name: JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-keys
              key: public
        - name: MAX_CONNECTIONS_PER_POD
          value: "1000"
        - name: HEARTBEAT_INTERVAL_SECONDS
          value: "30"
        - name: MESSAGE_HISTORY_LIMIT
          value: "100"
        - name: ENABLE_METRICS
          value: "true"
        - name: METRICS_PORT
          value: "9090"
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /ws/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /ws/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
  traffic:
  - percent: 100
    latestRevision: true