apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: data-analytics-service
  namespace: default
  annotations:
    run.googleapis.com/launch-stage: GA
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "2"
        autoscaling.knative.dev/maxScale: "100"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/vpc-access-connector: projects/PROJECT_ID/locations/REGION/connectors/vpc-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      containerConcurrency: 200
      timeoutSeconds: 300
      serviceAccountName: analytics-sa
      containers:
      - image: gcr.io/project-id/data-analytics:v1.8.0
        name: data-analytics
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: BIGQUERY_PROJECT
          value: "analytics-project"
        - name: BIGQUERY_DATASET
          value: "analytics_dataset"
        - name: PUBSUB_TOPIC
          value: "analytics-events"
        - name: CACHE_TTL_SECONDS
          value: "3600"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: connection-string
        - name: ENABLE_PROFILING
          value: "true"
        resources:
          limits:
            cpu: "4"
            memory: "8Gi"
          requests:
            cpu: "2"
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
  traffic:
  - percent: 100
    latestRevision: true