apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: payment-processing-service
  namespace: default
  annotations:
    run.googleapis.com/launch-stage: GA
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "2"
        autoscaling.knative.dev/maxScale: "50"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 500
      timeoutSeconds: 60
      serviceAccountName: payment-processor-sa
      containers:
      - image: gcr.io/project-id/payment-processor:v2.1.0
        name: payment-processor
        ports:
        - name: http1
          containerPort: 3000
        env:
        - name: STRIPE_API_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-secret
              key: api-key
        - name: PAYMENT_GATEWAY_URL
          value: "https://api.payment-gateway.com"
        - name: RETRY_ATTEMPTS
          value: "3"
        - name: LOG_LEVEL
          value: "info"
        resources:
          limits:
            cpu: "4"
            memory: "4Gi"
          requests:
            cpu: "2"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        startupProbe:
          httpGet:
            path: /startup
            port: 3000
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 30
  traffic:
  - percent: 100
    latestRevision: true