# Cloud Build configuration for AGI Egg ISR Router
# This file defines the build steps for Cloud Build

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/isr-router:$BUILD_ID'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/isr-router:latest'
      - '-f'
      - 'apps/intent-router/Dockerfile'
      - '--build-arg'
      - 'NODE_ENV=production'
      - '.'
    # Build from root directory to access all files

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/isr-router:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/isr-router:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy agi-egg-isr-router \
          --image us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/isr-router:$BUILD_ID \
          --region us-central1 \
          --platform managed \
          --service-account isr-router-sa@$PROJECT_ID.iam.gserviceaccount.com \
          --allow-unauthenticated \
          --min-instances 1 \
          --max-instances 100 \
          --cpu 4 \
          --memory 8Gi \
          --timeout 300 \
          --concurrency 1000 \
          --port 8080 \
          --set-env-vars="NODE_ENV=production" \
          --set-env-vars="SERVICE_NAME=agi-egg-isr-router" \
          --set-env-vars="SERVICE_VERSION=v3.1.0" \
          --set-env-vars="GCP_PROJECT_ID=$PROJECT_ID" \
          --set-env-vars="GCP_REGION=us-central1" \
          --set-env-vars="FIRESTORE_DATABASE=(default)" \
          --set-env-vars="ISR_CHUNK_SIZE=500" \
          --set-env-vars="ISR_SUMMARY_INTERVAL=5" \
          --set-env-vars="ISR_SESSION_TIMEOUT=300000" \
          --set-env-vars="IMS_CACHE_TTL=60000" \
          --set-env-vars="IMS_DEFAULT_MODEL=gemini-2.0-flash-exp" \
          --set-env-vars="AOL_DEFAULT_AUTONOMY=2" \
          --set-env-vars="AOL_MAX_RISK_SCORE=70" \
          --set-env-vars="ENABLE_TRACING=true" \
          --set-env-vars="ENABLE_METRICS=true" \
          --set-env-vars="LOG_LEVEL=info" \
          --set-secrets="GEMINI_API_KEY=gemini-api-key:latest" \
          --set-secrets="FIREBASE_CONFIG=firebase-config:latest" \
          --quiet

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'

# Images to push to Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/isr-router:$BUILD_ID'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/isr-router:latest'

# Timeout for the entire build
timeout: '1800s'